### ISSUE TITLE
Failing HalyardComplexSPARQLQueryTest.testSES2154SubselectOptional

### ISSUE THREAD

**Issue by asotona** [Merck/Halyard#1]
HalyardEvaluationStrategy does not support hash-joins and so it is not compliant with the case validated by HalyardComplexSPARQLQueryTest.testSES2154SubselectOptional

It is related: to <https://openrdf.atlassian.net/browse/SES-2154>
and <https://bitbucket.org/openrdf/sesame/commits/4fd3687977a7e801fa6ce681bd12ede799f35420>

**Comment by jindrichmynarz** [comment]
The culprit seems to be the Halyard's push strategy for query evaluation. When this strategy is used, the following minimal case behaves erroneously.

Load data on 10 persons into Halyard:

```ttl
PREFIX :       <http://example.com/>
PREFIX schema: <http://schema.org/>

:a a schema:Person .
:b a schema:Person .
:c a schema:Person .
:d a schema:Person .
:e a schema:Person .
:f a schema:Person .
:g a schema:Person .
:h a schema:Person .
:i a schema:Person .
:j a schema:Person .
``` 

Select 5 persons and optionally join with a non-existent property:

```sparql
PREFIX : <http://example.com/>
PREFIX schema: <http://schema.org/>

SELECT (COUNT(*) AS ?count)
WHERE {
  {
    SELECT ?person
    WHERE {
      ?person a schema:Person .
    }
    LIMIT 5
  }
  OPTIONAL {
    [] :nonexistent [] .
  }
}
```

We'd expect `?count` to be 5, but it is 0. The strategy probably starts evaluation with the `OPTIONAL` block, finding no results, instead of adhering to the bottom-up execution and starting with the sub-SELECT.
