### ISSUE TITLE
Can not deploy webapps (Halyard version 1.2)

### ISSUE THREAD

**Issue by earthquakesan** [Merck/Halyard#24]
Hi Adam! @asotona 

I've been trying out the last version of Halyard (version 1.2) recently and was able to run the scripts and rdf4j console. In particular, bulkload.sh, loading via rdf4j console, querying with rdf4j console and export.sh worked for me. I am working towards packing Halyard into docker images and adding it as a another triplestore to the [HOBBIT platform](https://github.com/hobbit-project).

However, when I am trying to deploy the webapps, I have the following warnings in the tomcat log (catalina.out):
```
22-Jul-2017 22:23:28.559 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jaxb-api.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jaxb-api.jar (No such file or directory)
...
22-Jul-2017 22:23:28.561 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/activation.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/activation.jar (No such file or directory)
...
22-Jul-2017 22:23:28.562 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jsr173_1.0_api.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jsr173_1.0_api.jar (No such file or directory)
...
22-Jul-2017 22:23:28.563 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jaxb1-impl.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jaxb1-impl.jar (No such file or directory)
...
22-Jul-2017 22:23:28.564 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/hdfs/lib/jaxb-api.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/hdfs/lib/jaxb-api.jar (No such file or directory)
...
```
It basically states that folders:
* hadoop-3.0.0-alpha4/share/hadoop/common/lib/
* hadoop-3.0.0-alpha4/share/hadoop/hdfs/lib

Does not contain the following jars:
* jaxb-api.jar
* jaxb1-impl.jar
* jsr173_1.0_api.jar

The jars which are there are:
* jaxb-api-2.2.11.jar
* jaxb-impl-2.2.3-1.jar
* jsr311-api-1.1.1.jar

The server starts, but I can not create repository or add any data to it.
Here are the versions of the software I use:
* Hadoop 3.0.0-alpha4 (I've tried 2.8.0, had the same error)
* HBase 1.2.6
* Tomcat 9.0.0.M22 (I've tried 8.5.16, had the same error)

The setenv.sh for tomcat is the same as in [the manual](https://merck.github.io/Halyard/tools.html):
```
export CLASSPATH="$CATALINA_HOME/lib/servlet-api.jar:"`hadoop classpath`:`hbase classpath`
```
I can see that the $CLASSPATH sets correctly on tomcat startup. Am I missing something?

**Comment by asotona** [comment]
Hi Ivan,that missing files warnings are usually OK. It is caused by invalid classpath entries in Hadoop and I've seen them in all distributions and versions I used. When the server starts and you can access the workbench - it should work. Do you see any other messages or errors while creating the repository?
Thanks,Adam
-------- Původní zpráva --------Od: Ivan Ermilov <notifications@github.com> Datum: 22.07.17  22:42  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Mention <mention@noreply.github.com> Předmět: [Merck/Halyard] Can not deploy webapps (Halyard version 1.2) (#24) 
Hi Adam! @asotona
I've been trying out the last version of Halyard (version 1.2) recently and was able to run the scripts and rdf4j console. In particular, bulkload.sh, loading via rdf4j console, querying with rdf4j console and export.sh worked for me. I am working towards packing Halyard into docker images and adding it as a another triplestore to the HOBBIT platform.
However, when I am trying to deploy the webapps, I have the following warnings in the tomcat log (catalina.out):
22-Jul-2017 22:23:28.559 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jaxb-api.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jaxb-api.jar (No such file or directory)
...
22-Jul-2017 22:23:28.561 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/activation.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/activation.jar (No such file or directory)
...
22-Jul-2017 22:23:28.562 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jsr173_1.0_api.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jsr173_1.0_api.jar (No such file or directory)
...
22-Jul-2017 22:23:28.563 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jaxb1-impl.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/common/lib/jaxb1-impl.jar (No such file or directory)
...
22-Jul-2017 22:23:28.564 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.scan Failed to scan [file:/home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/hdfs/lib/jaxb-api.jar] from classloader hierarchy
 java.io.FileNotFoundException: /home/ivan/Soft/hadoop/hadoop-3.0.0-alpha4/share/hadoop/hdfs/lib/jaxb-api.jar (No such file or directory)
...

It basically states that folders:

hadoop-3.0.0-alpha4/share/hadoop/common/lib/
hadoop-3.0.0-alpha4/share/hadoop/hdfs/lib

Does not contain the following jars:

jaxb-api.jar
jaxb1-impl.jar
jsr173_1.0_api.jar

The jars which are there are:

jaxb-api-2.2.11.jar
jaxb-impl-2.2.3-1.jar
jsr311-api-1.1.1.jar

The server starts, but I can not create repository or add any data to it.

Here are the versions of the software I use:

Hadoop 3.0.0-alpha4 (I've tried 2.8.0, had the same error)
HBase 1.2.6
Tomcat 9.0.0.M22 (I've tried 8.5.16, had the same error)

The setenv.sh for tomcat is the same as in the manual:
export CLASSPATH="$CATALINA_HOME/lib/servlet-api.jar:"`hadoop classpath`:`hbase classpath`

I can see that the $CLASSPATH sets correctly on tomcat startup. Am I missing something?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Can not deploy webapps (Halyard version 1.2) (#24)"}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/24"}}}

**Comment by earthquakesan** [comment]
Was problem with my browser, the rdf4j-workbench works fine. I'm closing the issue.

**Comment by yyz1989** [comment]
@earthquakesan thanks a lot for the answer. For me the case is tomcat simply cannot start as long as I insert the class paths via setenv.sh. I have no clue where it is hanging...

**Comment by asotona** [comment]
Hi Yang,
sorry for my late response.
Hadoop and HBase classpath is usually very messy with a lot of redundant and invalid entries, however it cannot be bundled with Halyard and it is necessary for Halyard to run in the Tomcat server. In your case there is probably some library on Hadoop classpath conflicting with Tomcat bootstrap libraries (a different version of a library or a different implementation of some service).
Tomcat should report such case in a form of an exception in the log (or directly in the console if you run it as "catalina run").
Do you experience such exception(s) (beside the invalid classpath entries described above?
Tomcat log and listing of your Hadoop and Hbase classpath should help to resolve it.
