### ISSUE TITLE
RDF4J-workbench, RDF4J-console behaviour

### ISSUE THREAD

**Issue by earthquakesan** [Merck/Halyard#26]
Hi Adam! @asotona 

There is a strange behavior regarding loading the data. What I would expect is:
1. If I load the data using bulkload into HBase table "benchmark10" it should be somehow accessible within rdf4j console.
--> this one works fine. I could load the data with bulkload into HBase and then query it with rdf4j console. No repository is created automatically, but I could create one with
```
create hbase
```
Where I specify "benchmark10" table and e.g. sparql querying works.
2. If I create repository in rdf4j-console, it should be available in rdf4j-workbench.
I would expect that rdf4j-console and rdf4j-workbench are connected (in the end they are talking to the same rdf4j-server). Console and workbench repositories are not connected at all. Is it normal behavior?
3. If I load the data using bulkload into HBase table "benchmark10" it should be somehow accessible within rdf4j workbench.
I could create repository the same way I did in rdf4j-console. However, the menu items are grayed out and I could not query the repo. At some point the items become accessible (I could not figure out when), and I can query the repo, however `Repository Size` is always shown as `Number of Statements: 0`, `Number of Labeled Contexts: 0`

I am using Halyard 1.2 at the moment (from releases). Hadoop 2.7.3 and HBase 1.2.6.

**Comment by asotona** [comment]
Hi Ivan,thanks for pointing this topic our.Halyard Bulk Load (as well as other Halyard command line tools) work with Hbase tables directly and they have no connection with the repositories declared in various instances of RDF4J Server and Console. Each instance of RDF4J Server and each running Console has its own local SYSTEM repository, where it stores all information about declared repositories. Even Console does not share that SYSTEM repository with any server. This situation requires to declare each repository in each of the Server and Console, even they point to the same Hbase tables.
I would propose to move also SYSTEM repository to a common Hbase table to provide shared repository management. However that woul require core implementation changes and most probably a fork of RDF4J Server and Console applications. And it is definitelly worth to investigate.
The third problem with the grayed menus in the RDF4J Workbench is probably independent issue. I've seen it too and I only found it is probably related to the browser cookies and probably some bug in the Workbench frotend. What helped me was restart of my browser and clean of the related cookies.
Thank you,Adam

-------- Původní zpráva --------Od: Ivan Ermilov <notifications@github.com> Datum: 30.09.17  14:03  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Mention <mention@noreply.github.com> Předmět: [Merck/Halyard] RDF4J-workbench, RDF4J-console behaviour (#26) 
Hi Adam! @asotona
There is a strange behavior regarding loading the data. What I would expect is:

If I load the data using bulkload into HBase table "benchmark10" it should be somehow accessible within rdf4j console.

--> this one works fine. I could load the data with bulkload into HBase and then query it with rdf4j console. No repository is created automatically, but I could create one with

create hbase

Where I specify "benchmark10" table and e.g. sparql querying works.

2. If I create repository in rdf4j-console, it should be available in rdf4j-workbench.

I would expect that rdf4j-console and rdf4j-workbench are connected (in the end they are talking to the same rdf4j-server). Console and workbench repositories are not connected at all. Is it normal behavior?

3. If I load the data using bulkload into HBase table "benchmark10" it should be somehow accessible within rdf4j workbench.

I could create repository the same way I did in rdf4j-console. However, the menu items are grayed out and I could not query the repo. At some point the items become accessible (I could not figure out when), and I can query the repo, however Repository Size is always shown as Number of Statements: 0, Number of Labeled Contexts: 0
I am using Halyard 1.2 at the moment (from releases). Hadoop 2.7.3 and HBase 1.2.6.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"RDF4J-workbench, RDF4J-console behaviour (#26)"}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/26"}}}

**Comment by asotona** [comment]
Hi Ivan,in my last reply I forgot to explain the missing repository statistics.Actually it is necessary to execute Halyard Stats tool to re-calculate the statistics after a bulk load. These materialized statistics are reflected also in the Worbench repository summary page. Halyard is fully distributed and targeted on very large datasets so any experiments to calculate (or estimate) statistics in real time failed or produced invalid numbers (within the 2s Workbench timeout). There is still an option to try to utilise Hbase custom co-processor, however I give it a small chance to work reliably.
Thanks,Adam
-------- Původní zpráva --------Od: Ivan Ermilov <notifications@github.com> Datum: 30.09.17  14:03  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Mention <mention@noreply.github.com> Předmět: [Merck/Halyard] RDF4J-workbench, RDF4J-console behaviour (#26) 
Hi Adam! @asotona
There is a strange behavior regarding loading the data. What I would expect is:

If I load the data using bulkload into HBase table "benchmark10" it should be somehow accessible within rdf4j console.

--> this one works fine. I could load the data with bulkload into HBase and then query it with rdf4j console. No repository is created automatically, but I could create one with

create hbase

Where I specify "benchmark10" table and e.g. sparql querying works.

2. If I create repository in rdf4j-console, it should be available in rdf4j-workbench.

I would expect that rdf4j-console and rdf4j-workbench are connected (in the end they are talking to the same rdf4j-server). Console and workbench repositories are not connected at all. Is it normal behavior?

3. If I load the data using bulkload into HBase table "benchmark10" it should be somehow accessible within rdf4j workbench.

I could create repository the same way I did in rdf4j-console. However, the menu items are grayed out and I could not query the repo. At some point the items become accessible (I could not figure out when), and I can query the repo, however Repository Size is always shown as Number of Statements: 0, Number of Labeled Contexts: 0
I am using Halyard 1.2 at the moment (from releases). Hadoop 2.7.3 and HBase 1.2.6.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"RDF4J-workbench, RDF4J-console behaviour (#26)"}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/26"}}}

**Comment by earthquakesan** [comment]
Thanks for the answer, makes things clear now -)
I will close the issue as rdf4j works as intended.
