### ISSUE TITLE
Repository Connection rollback() throws unsupported operation exception

### ISSUE THREAD

**Issue by elky87** [Merck/Halyard#33]
This code throws an unsupported operations exception:

```
 try (RepositoryConnection repCon = repo.getConnection()) {
            repCon.begin();
            repCon.add(vf.createStatement(subject, predicate, object, context));
            repCon.rollback() //exception
        }
```

This is especially problematic because the standard behaviour of HTTPRepositoryConnection when using in combination with a try-with-resource statement is to call rollback() when a transaction is still active and close() is called

RDF4J HTTPRepository code:

```
@Override
public void close()
		throws RepositoryException
	{
		if (isActive()) {
			logger.warn("Rolling back transaction due to connection close", new Throwable());
			rollback();
		}

		super.close();
	}
```

**Comment by asotona** [comment]
Right, it cause a problem, even the exception is relevant. I'll change it.

**Comment by elky87** [comment]
just to be sure. Does rollback really roll back all the uncommited changes now?

**Comment by asotona** [comment]
Unfortunatelly no, it does not support transactions. If you need transactional processing, use Bulk Load and Bulk Update tools, where the physical execution of the all operations is in a single final step, so any error or cancelation does not produce partial changes.
Thanks,Adam
-------- Původní zpráva --------Od: Christoph Ellinger <notifications@github.com> Datum: 24.10.17  16:15  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, State change <state_change@noreply.github.com> Předmět: Re: [Merck/Halyard] Repository Connection rollback() throws
  unsupported operation exception (#33) 
just to be sure. Does rollback really roll back all the uncommited changes now?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@elky87 in #33: just to be sure. Does rollback really roll back all the uncommited changes now?"}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/33#issuecomment-339004880"}}}
