### ISSUE TITLE
Use RDF4J 2.3.2

### ISSUE THREAD

**Issue by peterjohnlawrence** [Merck/Halyard#44]
Is there any reason why RDF4J 2.3.2 (ie the latest) cannot be used? This release of RDF4J has fixed some other issues, possibly unrelated to Halyard

**Comment by asotona** [comment]
I hope there is no technical reason.As Halyard is not just using RDF4J API, but it also implements and provides RDF4J SPI, and it complies to its tests - it is not as easy as just write a differen version in pom.xmlHowever it is planned to update RDF4J periodically and you may expect it happens soon.
Thank you for the report,Adam
-------- Původní zpráva --------Od: Lawrence <notifications@github.com> Datum: 28.06.18  12:22  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Předmět: [Merck/Halyard] Use RDF4J 2.3.2 (#44) 
Is there any reason why RDF4J 2.3.2 (ie the latest) cannot be used? This release of RDF4J has fixed some other issues, possibly unrelated to Halyard

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Use RDF4J 2.3.2 (#44)"}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/44"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Merck/Halyard/issues/44",
"url": "https://github.com/Merck/Halyard/issues/44",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Use RDF4J 2.3.2 (#44)",
"sections": [
{
"text": "",
"activityTitle": "**Lawrence**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@peterjohnlawrence",
"facts": [
{
"name": "Repository: ",
"value": "Merck/Halyard"
},
{
"name": "Issue #: ",
"value": 44
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Merck/Halyard\",\n\"issueId\": 44,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Merck/Halyard\",\n\"issueId\": 44\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Merck/Halyard/issues/44"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 351045045\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by peterjohnlawrence** [comment]
Understood. I will close this as it is not therefore an issue.

**Comment by peterjohnlawrence** [comment]
Understood. I will close this as it is not therefore an issue.
