### ISSUE TITLE
Consider adding a leading "salt" to your row keys

### ISSUE THREAD

**Issue by pulquero** [Merck/Halyard#55]
I've noticed alot of hotspotting when running some queries. It seems a getStatements() is going to hit a single region. Consider adding a leading salt to your row keys - I've always found that this helps quite a bit with performance when using HBase. It should spread the load over multiple regions and complement your push strategy - you will be able to start pushing as soon as any of the regions start to return data.

As your row key is already a list of hashes, it should be fairly easy to calculate a hash for the entire row and mod by N, the number of salt buckets. getStatements() then issues N parallel scans, one for each salt, to retrieve all the requested statements. Presplit becomes trivial to calculate - just split on salt boundaries.

The existing halyard:forkAndFilter predicate sort of does something similar to a salt, but only distributes the computation, not the data, and only for map-reduce. With salts, you can run M map-reduce jobs per salt bucket.

**Comment by asotona** [comment]
Actual mapping is designed to spread the load for more complex, multi-join queries and for systems that perform many different queries, from many users, through multiple endpoints. 
As I understand you observe hotspotting when asking for a single statement pattern and you propose how to distribute such load.
Technically it would be possible to use such a kind of "salt" hash prefix, so each single actual scan would split into N scans, however it will significantly affect performance of multi-join queries.
Also halyard:forkAndFilter would not be able to utilise this feature as it operates with query variables level (not with statement patterns of the query). 
If you mostly require a bulk export of a single statement pattern and you want to do it fast - I can recommend you to create a custom HBase MapReduce tool that would setup the mappers based on the provided scan. Such approach is used in Halyard Stats and Halyard Summary tools. Let me know if such tool would be useful for you.

Thanks,
Adam

**Comment by pulquero** [comment]
The queries in question were bulk multi-join with sub-select group-by using forkAndFilter. Only even one region seemed to be hit at a time, so I wondered if distributing getStatements() would help. I see all the joins are standard rdf4j 2-way Joins. The rdf4j Federation sail has a NaryJoin in its algebra and ParallelJoin evaluation. Maybe the key is to do n-way parallel joins to effectively spread the load and flatten the query tree?

**Comment by pulquero** [comment]
I have thought further about this and it occurred to me that great efficiencies could be made if the HBase schema was changed to store the triple across s,p,o,c columns. Then a scan for <subj> <pred> ?obj could just return the data in the 'o' column rather than the entire triple since <subj> and <pred> are already known. Atm this isn't possible since a row key doesn't uniquely identify a triple, but this could be rectified by appending something akin to a UUID v1 to the end, i.e. [mac-address][timestamp].  And is there any reason to use SHA1 for the hashes? I don't think there is any reason to use a cryptographic hash, in which case something like 128bit spookyhash should be sufficient, faster and save some key space. Interested to know what your thoughts are, have you previously considered something like this?

**Comment by asotona** [comment]
Hi,I would suggest you to read following articles to better understand Halyard architecture and reasons for that architecture:https://www.linkedin.com/pulse/inside-halyard-1-triples-keys-columns-values-upside-adam-sotonahttps://www.linkedin.com/pulse/inside-halyard-2-when-one-working-thread-enough-push-versus-sotonahttps://www.linkedin.com/pulse/inside-halyard-3-sipping-river-through-drinking-straws-adam-sotonahttps://www.linkedin.com/pulse/inside-halyard-4-bulk-operations-shifting-mountain-adam-sotonahttps://www.linkedin.com/pulse/inside-halyard-5-sparql-federation-without-border-controls-sotonahttps://www.linkedin.com/pulse/inside-halyard-6-statistics-based-acceleration-sparql-adam-sotona
Feel free to ask if you will still have questions related to the actual Halyard architecture.Also if you would like to implement alternative mapping, we may discuss pros and cons and eventually compare it on benchmarks.
Thanks,Adam
-------- Původní zpráva --------Od: pulquero <notifications@github.com> Datum: 24.01.19  16:38  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Comment <comment@noreply.github.com> Předmět: Re: [Merck/Halyard] Consider adding a leading "salt" to your row keys (#55) 
The queries in question were bulk multi-join with sub-select group-by using forkAndFilter. Only even one region seemed to be hit at a time, so I wondered if distributing getStatements() would help. I see all the joins are standard rdf4j 2-way Joins. The rdf4j Federation sail has a NaryJoin in its algebra and ParallelJoin evaluation. Maybe the key is to do n-way parallel joins to effectively spread the load and flatten the query tree?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pulquero in #55: The queries in question were bulk multi-join with sub-select group-by using forkAndFilter. Only even one region seemed to be hit at a time, so I wondered if distributing getStatements() would help. I see all the joins are standard rdf4j 2-way Joins. The rdf4j Federation sail has a NaryJoin in its algebra and ParallelJoin evaluation. Maybe the key is to do n-way parallel joins to effectively spread the load and flatten the query tree?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/55#issuecomment-457241892"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Merck/Halyard/issues/55#issuecomment-457241892",
"url": "https://github.com/Merck/Halyard/issues/55#issuecomment-457241892",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
