### ISSUE TITLE
More compact triple format

### ISSUE THREAD

**Issue by pulquero** [Merck/Halyard#56]
I've modified the triple byte-encoding from using N-triples to be something more turtle-like. The corresponding reduction in column name length reduces disk i/o and network bandwidth leading to faster overall performance. I measured a 15% reduction in time in the reducer stage of my bulk loads. Details here: https://github.com/pulquero/Halyard/tree/compact-datatypes

**Comment by asotona** [comment]
That is interesting, my experiments with custom triples compaction led to the experience that HBase encoding and block compression does already great job. What is the difference in the HBase table size for compacted triples?Prefix translation of IRIs has a drawback that they are no more globally unique. Forever fixed and hard-coded set of standard prefixes might work, however your solution makes stored data dependent on the actual local Halyard configuration. You'll have to assure that the prefix list will never change after the dataset is created and that you'll never merge datasets with different prefix lists. Actual Halyard mapping is universal and backward and forward compatible. It allows to transfer, clone and merge dataset snapshots across different clusters with different configurations, and across different Halyard versions (since its very first release).

-------- Původní zpráva --------Od: pulquero <notifications@github.com> Datum: 08.02.19  21:03  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Předmět: [Merck/Halyard] More compact triple format (#56) 
I've modified the triple byte-encoding from using N-triples to be something more turtle-like. The corresponding reduction in column name length reduces disk i/o and network bandwidth leading to faster overall performance. I measured a 15% reduction in time in the reducer stage of my bulk loads. Details here: https://github.com/pulquero/Halyard/tree/compact-datatypes

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"More compact triple format (#56)"}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/56"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Merck/Halyard/issues/56",
"url": "https://github.com/Merck/Halyard/issues/56",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pulquero** [comment]
HDFS du shows about a 6% reduction in disk space. The code uses a hard-coded set of common namespaces, plus an optional external file. Without the external file, the mapping is still universal. It is still possible to merge datasets if you also merge the external files too, assuming no-conflicts. You can add to the prefix list fine after data creation, just not remove from it, well even that would be possible if you checked you no longer had any IRIs that used the prefix. The current format could be used by default, with an option to use the new format.

**Comment by asotona** [comment]
Change in encoding/compression must be still considered as incompatible change. I'm considering to do such change and switch to a new encoding and do the new Halyard major incompatible release, however there must be several conditions met. The new encoding must remain strictly static and generic, with no ambiguity, no multiple or alternative encodings. To decide to implement such change I would like to pass at least 15% savings threshold to pay back all the incompatibility and upgrades of the existing systems costs.Your proposal to replace some well known prefixes is a good start. I can imagine to evaluate some fixed-dictionary text compression methods and find the best pre-trained generic dictionary (or other short-text compression methods), and test it on real data with consideration of various HBase compression options.

Thanks,Adam
-------- Původní zpráva --------Od: pulquero <notifications@github.com> Datum: 08.02.19  23:11  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Comment <comment@noreply.github.com> Předmět: Re: [Merck/Halyard] More compact triple format (#56) 
HDFS du shows about a 6% reduction in disk space. The code uses a hard-coded set of common namespaces, plus an optional external file. Without the external file, the mapping is still universal. It is still possible to merge datasets if you also merge the external files too, assuming no-conflicts. You can add to the prefix list fine after data creation, just not remove from it, well even that would be possible if you checked you no longer had any IRIs that used the prefix. The current format could be used by default, with an option to use the new format.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pulquero in #56: HDFS du shows about a 6% reduction in disk space. The code uses a hard-coded set of common namespaces, plus an optional external file. Without the external file, the mapping is still universal. It is still possible to merge datasets if you also merge the external files too, assuming no-conflicts. You can add to the prefix list fine after data creation, just not remove from it, well even that would be possible if you checked you no longer had any IRIs that used the prefix. The current format could be used by default, with an option to use the new format."}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/56#issuecomment-461964510"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Merck/Halyard/issues/56#issuecomment-461964510",
"url": "https://github.com/Merck/Halyard/issues/56#issuecomment-461964510",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pulquero** [comment]
I've made some more improvements, and now added dictionary encoding of IRIs too for well known vocabularies. An option you could consider is having a flag to switch between legacy and any new encoding. That way it would work out-the-box for existing installations, and allow the new encoding to be turned-on explicitly.

**Comment by asotona** [comment]
I've just performed simulation of pre-deflated statements (using pre-trained) dictionary. Despite the pretty nice results of each single statement compression, target gzipped block has reacted exactly opposite, it has been 8x bigger. So deflate-like pre-compression is out of the game.
Then I tried just string prefix replacements, collected list of prefixes that reduced test set of the statements by 27%. However the final saving is less then 5%, when they are aggregated into a larger gzipped block. Based on that finding I still thing gzip compression still shows great results when compressing frequently repeating texts and the results are not dependent on the success rate of pre-selected prefixes.
 
-------- Původní zpráva --------Od: pulquero <notifications@github.com> Datum: 11.02.19  11:54  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Comment <comment@noreply.github.com> Předmět: Re: [Merck/Halyard] More compact triple format (#56) 
I've made some more improvements, and now added dictionary encoding of IRIs too for well known vocabularies. An option you could consider is having a flag to switch between legacy and any new encoding. That way it would work out-the-box for existing installations, and allow the new encoding to be turned-on explicitly.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pulquero in #56: I've made some more improvements, and now added dictionary encoding of IRIs too for well known vocabularies. An option you could consider is having a flag to switch between legacy and any new encoding. That way it would work out-the-box for existing installations, and allow the new encoding to be turned-on explicitly."}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/56#issuecomment-462286935"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Merck/Halyard/issues/56#issuecomment-462286935",
"url": "https://github.com/Merck/Halyard/issues/56#issuecomment-462286935",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pulquero** [comment]
The 5% reduction seems consistent with what I got in terms of disk-space. So HFile compression is pretty effective. But, how about map-reduce jobs? This is where I got a bigger reduction in time from using less reducers than normal. Is the gain from the mappers writing out less? The number of reducers is determined by number of regions calculated by pre-split, right?

**Comment by asotona** [comment]
When considering space savings and secondary also computation savings would be useful to test shorter and faster hash function? Assuming hash part of the key is barely compressible, for example 64bit FNV hash instead of 160bit SHA1 could theoretically help more than pre-compressing of the statements.Actual 160bit SHA1 is almost non-coliding, so all side-effects of the hash size reduction must be considered, however I can imagine there is higher chance to pass the threshold for incompatible change.Several percent savings were actually not high on Halyard priority list, however if there is strong demand I can look at it more deeply.
Regarding the alternate encoding switch - I'm not fun of multiple internal implementations. It would introduce huge tests and compatibility matrix, maintenance and bug resolution nightmares, for almost no user benefits. 
-------- Původní zpráva --------Od: pulquero <notifications@github.com> Datum: 11.02.19  11:54  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Comment <comment@noreply.github.com> Předmět: Re: [Merck/Halyard] More compact triple format (#56) 
I've made some more improvements, and now added dictionary encoding of IRIs too for well known vocabularies. An option you could consider is having a flag to switch between legacy and any new encoding. That way it would work out-the-box for existing installations, and allow the new encoding to be turned-on explicitly.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pulquero in #56: I've made some more improvements, and now added dictionary encoding of IRIs too for well known vocabularies. An option you could consider is having a flag to switch between legacy and any new encoding. That way it would work out-the-box for existing installations, and allow the new encoding to be turned-on explicitly."}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/56#issuecomment-462286935"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Merck/Halyard/issues/56#issuecomment-462286935",
"url": "https://github.com/Merck/Halyard/issues/56#issuecomment-462286935",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pulquero** [comment]
I'm actually running a load right now with a 256-bit hash so I can assume no collisions and have separate s,p,o,c columns to see what that does. This will increase the number of cells, but each cell itself will be smaller in size (https://github.com/pulquero/Halyard/tree/columns). Plus, you can just return the columns you care about. This should increase query performance, but need to check it doesn't kill load speed first. Probably 192bit is fine, but I thought I would start on the high-side.

**Comment by asotona** [comment]
MapReduce is configured to compress map output using Gzip (see halyard-defaults.xml).Number of bulk load reducers correspond to number of regions.
 
-------- Původní zpráva --------Od: pulquero <notifications@github.com> Datum: 11.02.19  15:19  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Comment <comment@noreply.github.com> Předmět: Re: [Merck/Halyard] More compact triple format (#56) 
The 5% reduction seems consistent with what I got in terms of disk-space. So HFile compression is pretty effective. But, how about map-reduce jobs? This is where I got a bigger reduction in time from using less reducers than normal. Is the gain from the mappers writing out less? The number of reducers is determined by number of regions calculated by pre-split, right?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pulquero in #56: The 5% reduction seems consistent with what I got in terms of disk-space. So HFile compression is pretty effective. But, how about map-reduce jobs? This is where I got a bigger reduction in time from using less reducers than normal. Is the gain from the mappers writing out less? The number of reducers is determined by number of regions calculated by pre-split, right?"}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/56#issuecomment-462343534"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Merck/Halyard/issues/56#issuecomment-462343534",
"url": "https://github.com/Merck/Halyard/issues/56#issuecomment-462343534",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pulquero** [comment]
My 256bit experiment was a disaster, the load was so slow I had to kill the job in the end. But, it did make me think about hashing and I wondered if variable hashing could make a big difference. Take the SPO index, S has a high cardinality so should use a 160/192bit hash, for a given S, P has a much lower cardinality so say 32/56/64bit hash should be ample. For a given SP, an 8bit hash for O is probably fine. That is a reduction of over 50% in key size. Similarly for OSP, O 192, S 128/192, P 32. POS, P 32/64, O 192, S 128/192. For CXXX, C 32/64. Also, shorts can be used to store the length of S,P,C in the column names instead of ints as 16K is well ample length for any IRI or BNode identifier.

**Comment by asotona** [comment]
I created a branch with only 64bit fast hash (vs actual 160bit) and I would like to make performance and size comparison tests soon. Halyard is designed to resolve conflicting hashes so the question would be how many conflicts, how well is would perform, and how big will be savings.I still prefer to use one "generally optimal" hash for all to avoid later headaches.
-------- Původní zpráva --------Od: pulquero <notifications@github.com> Datum: 12.02.19  13:13  (GMT+01:00) Komu: Merck/Halyard <Halyard@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Comment <comment@noreply.github.com> Předmět: Re: [Merck/Halyard] More compact triple format (#56) 
My 256bit experiment was a disaster, the load was so slow I had to kill the job in the end. But, it did make me think about hashing and I wondered if variable hashing could make a big difference. Take the SPO index, S has a high cardinality so should use a 160/192bit hash, for a given S, P has a much lower cardinality so say 32/56/64bit hash should be ample. For a given SP, an 8bit hash for O is probably fine. That is a reduction of over 50% in key size. Similarly for OSP, O 192, S 128/192, P 32. POS, P 32/64, O 192, S 128/192. For CXXX, C 32/64. Also, shorts can be used to store the length of S,P,C in the column names instead of ints as 16K is well ample length for any IRI or BNode identifier.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Merck/Halyard","title":"Merck/Halyard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Merck/Halyard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pulquero in #56: My 256bit experiment was a disaster, the load was so slow I had to kill the job in the end. But, it did make me think about hashing and I wondered if variable hashing could make a big difference. Take the SPO index, S has a high cardinality so should use a 160/192bit hash, for a given S, P has a much lower cardinality so say 32/56/64bit hash should be ample. For a given SP, an 8bit hash for O is probably fine. That is a reduction of over 50% in key size. Similarly for OSP, O 192, S 128/192, P 32. POS, P 32/64, O 192, S 128/192. For CXXX, C 32/64. Also, shorts can be used to store the length of S,P,C in the column names instead of ints as 16K is well ample length for any IRI or BNode identifier."}],"action":{"name":"View Issue","url":"https://github.com/Merck/Halyard/issues/56#issuecomment-462736808"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Merck/Halyard/issues/56#issuecomment-462736808",
"url": "https://github.com/Merck/Halyard/issues/56#issuecomment-462736808",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by asotona** [comment]
Preliminary evaluation showed approximately 12% savings with 64bit hash (however not counting HBase prefix key compression savings, which are bigger for larger keys).
I would like to combine your encoding proposal with shorter hashes, and optionally also with Snappy instead of GZ compression. It has potential to became a new faster and smaller mapping for Halyard 3.0

**Comment by asotona** [comment]
Unfortunately preliminary 12% done by presplit estimation was far from reality. I've tested real combined effect of 64bit hash and shortening the prefixes with only 7.7% savings.
Without more significant improvement it is not worth to break Halyard compatibility and force users to update/re-index all existing setups.
