### ISSUE TITLE
HBaseSail is not safe for concurrent use

### ISSUE THREAD

**Issue by pulquero** [Merck/Halyard#61]
HBase sail connections currently share a single HTable instance. HTable is known not to be thread-safe (see the javadoc). Therefore it is not safe to use multiple connections at the same time.

**Comment by asotona** [comment]
HTable instance is perfectly thread safe for parallel read operations, which feature is heavily utilised and verified by HalyardEvaluationStrategy.
The only "unsafe" are parallel writes and deletes (SPARQL Update operations). 
All actual Halyard tools use single connection only and HalyardEvaluationStrategy architecture limits single SPARQL Update writes to a single thread, so the HTable write contention does not occur.

Without a specific use case / failing test case it is hard to address your thread safety concerns, however I may expect that you are using the Java API directly, asking for two connections of the same SAIL and perform write or delete operations on both simultaneously from different threads.

Proposed "blind" fix options:
- Describe threading issue in Halyard javadoc and recommend to use multiple SAIL instances (instead of connections) for parallel write operations.
- Construction of HTable for each SAIL connection is out of the game due to the significant performance effects and HBase connection limits. Ideally the HTable should be "forked" just for writes, and only when the writes are done simultaneously.
- Synchronisation of HTable writes and deletes by a mutex or synchronised section should do the job. Blocking should be minimal due to the underlying buffer and deadlocks should be avoided as it would be applied on the low API level.
- Upgrade to HBase 2.0, where HTable is thread safe, however unfortunately HBase 2.0 is still not a part of major enterprise Hadoop distributions, so not yet even in plans for existing Hadoop deployments.

**Comment by pulquero** [comment]
You are right, my use case was using the RDF4J API directly and doing concurrent updates. Note also there maybe a problem with reads too, as the javadoc specifically states

> This class is NOT thread safe for reads nor writes.
  In the case of writes (Put, Delete), the underlying write buffer can
  be corrupted if multiple threads contend over a single HTable instance.
  In the case of reads, some fields used by a Scan are shared among all threads.

Also note that construction of HTable is in fact cheap. From experience, I have had no issues with using 100's of concurrent HTable instances. On the other-hand, Connection is expensive, very expensive, you only want and need one of those.

**Comment by asotona** [comment]
Well, I've dived into the HBase code and the only contention may happen when the very first call of the HTable.getBufferedMutator() is done very precisely synchronously.
The only pace where it can be called from HBaseSail is in put() method.
Deletes are also thread safe and reads as well. 
HBaseSail does not alter any HTable properties lazily, so these kind of threading issues are also out of the scope.

**Comment by asotona** [comment]
BufferedMutator is working synchronously, so wrapping the whole "put" into a synchronous block would not cause any bottleneck.
